# Generated by Django 3.2.4 on 2022-01-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('rating', models.FloatField()),
                ('release_date', models.CharField(max_length=4)),
                ('duration', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
